version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.0
        platform: linux/amd64
        ports:
            - '2181:2181'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        networks:
            - kafka-net

    kafka1:
        image: confluentinc/cp-kafka:7.3.0
        hostname: kafka1
        ports:
            - '9092:9092'
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        networks:
            - kafka-net

    kafka2:
        image: confluentinc/cp-kafka:7.3.0
        hostname: kafka2
        ports:
            - '9093:9092'
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:9093
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        networks:
            - kafka-net

    kafka-tools:
        image: confluentinc/cp-kafka:7.3.0
        platform: linux/amd64
        hostname: kafka-tools
        depends_on:
            - kafka1
            - kafka2
        entrypoint:
            - /bin/bash
            - -c
        command: >
            echo "Starting Kafka tools container..." &&
            sleep 30 &&
            kafka-topics --bootstrap-server kafka1:29092 --list &&
            tail -f /dev/null
        networks:
            - kafka-net

    postgres:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: aman
            POSTGRES_PASSWORD: root
            POSTGRES_DB: instagram
        ports:
            - '5433:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - kafka-net

    redis:
        image: redis:7
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - kafka-net

    backend1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend1
        environment:
            NODE_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: aman
            DB_PASSWORD: root
            DB_NAME: instagram
            REDIS_URL: redis://redis:6379
        depends_on:
            - postgres
            - redis
        networks:
            - kafka-net

    backend2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend2
        environment:
            NODE_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USERNAME: aman
            DB_PASSWORD: root
            DB_NAME: instagram
            REDIS_URL: redis://redis:6379
        depends_on:
            - postgres
            - redis
        networks:
            - kafka-net

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - backend1
            - backend2
        networks:
            - kafka-net

volumes:
    pgdata:

networks:
    kafka-net:
        driver: bridge
